apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    {{  .Values.service.label }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      nodePort: {{  .Values.service.nodeport }}
      protocol: TCP
    
  selector:
     app: {{ .Values.name  }}
